apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dashy
resources:
   - ../../base/dashy

patches:
   -target:
      kind: Ingress
    patch: |-
       - op: replace
         path: /spec/rules/0/http/paths/0/backend/port/number
         value: 9100
